export const USERINFO_VERIFY = 'USERINFO_VERIFY';
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';
export const COURSEINFO_REQUEST = 'COURSEINFO_REQUEST';
export const COURSEINFO_SUCCESS = 'COURSEINFO_SUCCESS';
export const COURSEINFO_FAILURE = 'COURSEINFO_FAILURE';
